---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootwachtwoord
  MYSQL_USER: budibase
  MYSQL_PASSWORD: budibase123
  MYSQL_DATABASE: iac_tracker
