---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budibase
  namespace: app
  labels:
    app: budibase
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budibase
  template:
    metadata:
      labels:
        app: budibase
        tier: frontend
    spec:
      containers:
        - name: budibase
          image: budibase/budibase:latest
          ports:
            - containerPort: 80
          env:
            - name: MINIO_URL
              value: "http://localhost:9000"
            - name: COUCH_DB_URL
              value: "http://localhost:5984"
          volumeMounts:
            - name: budibase-data
              mountPath: /data
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: budibase-data
          persistentVolumeClaim:
            claimName: budibase-pvc
