---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: budibase-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
