---
apiVersion: v1
kind: Service
metadata:
  name: budibase
  namespace: app
  labels:
    app: budibase
    tier: frontend
spec:
  type: NodePort
  selector:
    app: budibase
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30088
