---
apiVersion: v1
kind: Service
metadata:
  name: dbf-api
  namespace: app
  labels:
    app: dbf-api
    tier: api
spec:
  type: NodePort
  selector:
    app: dbf-api
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30090
